### ISSUE TITLE
Option to split the panel in the current tab instead of opening a new tab everytime.

### ISSUE THREAD

**Issue by sunnysetia93** [elrumordelaluz/iterm-tab#1]
Hi @elrumordelaluz 

First of all, Thanks for this module. I thought of writing my own but then I found this one. 👍 

I feel there can be a need where user wants to split the tab vertically/horizontally instead of creating a new tab each time.
This option is available in the iterm2 script.

Thanks

**Comment by elrumordelaluz** [comment]
Hi @sunnysetia93, thanks for open the _Issue_.

Sounds pretty valid your request. Will give an eye asap. Also PR super welcome in case you want to.

**Comment by sunnysetia93** [comment]
Sure. I'll pick this up and will raise a PR asap.

**Comment by elrumordelaluz** [comment]
> Sure. I'll pick this up and will raise a PR asap.

awesome!

**Comment by sunnysetia93** [comment]
Raised a pull request. Kindly Check #2

**Comment by elrumordelaluz** [comment]
Thanks for the PR!

Should be available on 📦  `iterm-tab@0.4.0`. Let me know in any case.
