### ISSUE TITLE
Possible to run this as npm script from package.json?

### ISSUE THREAD

**Issue by wrabit** [elrumordelaluz/iterm-tab#3]
i.e. npm run dev (opens x 3 server tabs)

**Comment by elrumordelaluz** [comment]
Hi @wrabit, thanks for open the _Issue_.

Mind expanding a little your description? Did you look at the [example](https://github.com/elrumordelaluz/iterm-tab/blob/master/test.js)?

**Comment by wrabit** [comment]
Thanks, this was what I was looking for https://github.com/mklement0/ttab

**Comment by elrumordelaluz** [comment]
cool!
